MODEL:
  PRETRAIN_CHOICE: 'clip'
  PRETRAIN_PATH_T: '/13994058190/WYH/PTH/vitb_16_224_21k.pth'
  TRANSFORMER_TYPE: 'ViT-B-16'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  RE: 0
  RE_LAYER: 1
  DIRECT: 1
  STAGE: 2
  SIE_COE: 1.0
  ID_LOSS_WEIGHT: 0.25
  TRIPLET_LOSS_WEIGHT: 1.0
  PREFIX_NUM: 10

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: '/13994058190/WYH/DATA/data_pretrain'

SOLVER:
  BASE_LR: 0.00035
  WARMUP_ITERS: 5
  MAX_EPOCHS: 60
  OPTIMIZER_NAME: 'Adam'
  STEPS: [ 30, 50 ]
  GAMMA: 0.1
  IMS_PER_BATCH: 64

TEST:
  IMS_PER_BATCH: 64
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: "nothing"

OUTPUT_DIR: './RGBNT201/TOP-ReID-2'

